### ISSUE TITLE
save sentence embeddings

### ISSUE THREAD

**Issue by shahbazsyed** [yufengm/SelfAttentive#4]
Hi,
Can you kindly let me know how to / (where in the code) export the sentence embeddings of the training dataset ? 

Thanks!

**Comment by yufengm** [comment]
https://github.com/yufengm/SelfAttentive/blob/4756636fb585e44abcc20617818b6a6375a6eff9/model.py#L91

The BM variable should be the embeddings for sentences within one batch.
